name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Linting
      run: |
        cd backend
        npm run lint  # Make sure you have a lint script in package.json

    - name: Run Tests
      run: |
        cd backend
        npm test  # Ensure you have test cases set up

    - name: Build Docker image
      run: |
        docker build -t finsmart-backend ./backend
